### PR TITLE
[42] created NSHMInversionRunner

### PR DESCRIPTION
**Pull request by voj**
implements #42 apart from python wrapper

### CODE REVIEW

**Review by chrisbc — COMMENTED** [review]
Hi @voj Were you going to add the python gateway interface - of leave that for me to do?

**Comment by voj** [comment]
> 
> 
> Hi @voj Were you going to add the python gateway interface - of leave that for me to do?

@chrisbc I was going to leave that to you since I can't really test it. But I can also give it a whirl

**Comment by voj** [comment]
@chrisbc python gateway is done

**Review by chrisbc — APPROVED** [review]
Nice! Good call consolidating this into one class

**Pull request merged**
