### PR TITLE
Chrisbc/129 prepare inversions

### PR DESCRIPTION
**Pull request by chrisbc**

### CODE REVIEW

**Comment by chrisbc** [comment]
@voj Ready now - there are a couple minor of things I"d do differently but I'm keen to get this in Matt's hands :) 

I'll fix up those conflict errors ....

**Review by voj — COMMENTED** [review]
Looks good to me in general. We still need to decide which localisation approach we choose. And we're hard-coding a few things that might have to be dynamic. It looks like the code now no longer supports TVZ and downdips

**Comment by chrisbc** [comment]
>  It looks like the code now no longer supports TVZ and downdips

@voj Yes  - actually I'm going to sort out a couple now, so there'll be a 2nd review - sorry

**Comment by chrisbc** [comment]
@voj - can you please re-review. This is done I now think...

**Review by voj — APPROVED** [review]
Looks good

**Pull request merged**
