### PR TITLE
Chrisbc/141 upstream task inputs

### PR DESCRIPTION
**Pull request by chrisbc**
includes:
 - report additions

### CODE REVIEW

**Review by chrisbc — COMMENTED** [review]
I'm doing more on these, but this is all WIP and can go to master IMO

**Comment by voj** [comment]
This PR includes commits that should not be merged in master (hazard calc).

**Comment by voj** [comment]
The rest looks good.

**Review by voj — CHANGES_REQUESTED** [review]
See my comments. Hazard calc changes should go before merging because they don't work properly yet and are out of date as well.

**Comment by chrisbc** [comment]
> See my comments. Hazard calc changes should go before merging because they don't work properly yet and are out of date as well.

Hi @voj thanks for your assistance cleaning this up ! :) gonna merge now....

**Pull request merged**
