### PR TITLE
Chrisbc/new opensha build

### PR DESCRIPTION
**Pull request by chrisbc**
builds against new opensha/master.

### CODE REVIEW

**Comment by chrisbc** [comment]
@voj -  I suggest we do a squash merge to collapse all that commit history. 

The travis file needs fixing - can I leave that to you please?

**Comment by kevinmilner** [comment]
@chrisbc and @voj:

I have (yet again) redone the multi-project gradle setup, getting things like fatJar to work without lots of code duplication. First, 'build-common.gradle' is back in the top level project. Then you need to default 'parentProject' in your project, and should be able to greatly simplify your downstream build file. That can look similar to [this from opensha-dev](https://github.com/opensha/opensha-dev/blob/2021_05-upstream-repo-merge-refactor/build.gradle):

```
/*
 * opensha-dev dependencies
 */

apply plugin: 'java-library'

ext {
    parentProject = 'opensha'
}

apply from: '../opensha/build-common.gradle'

dependencies {

    implementation 'org.apache.pdfbox:pdfbox:2.0.6'
    implementation 'org.apache.commons:commons-collections4:4.1'
    api 'org.apache.commons:commons-compress:1.15'
    api 'uk.me.berndporr:iirj:1.0'
    implementation 'org.apache.spark:spark-core_2.12:3.0.1'
    implementation 'org.apache.spark:spark-mllib_2.12:3.0.1'
    implementation 'com.github.haifengl:smile-core:2.6.0'
    
    /* no remote repo */
    implementation files('lib/EventWebService.jar')
    api files('lib/flanagan.jar') // FFT and PSD library along with other tools

    implementation project(path: ':opensha')

    testImplementation 'junit:junit:4.12'
}
```

**Review by chrisbc — COMMENTED** [review]
@voj this is a **Huge PR.** But everything here is well tested. I haven't run off master/main for over 3months now!

**Comment by voj** [comment]
From what I can see this is all OK.

**Pull request merged**
